var five = 5;
var ten = 10;
console.log("test 1 :five equal to 5?");
console.log(five == 5);
console.log("test 2 :ten is equal to 10?");
console.log(ten == 10);
console.log("test 3 :five is not equal to 10?");
console.log(five != 10);
console.log("test 4 :10 is greater than 5?");
console.log(ten > 5);
console.log("test 5 :5 is smaller than 10");
console.log(five < 10);
console.log("test 6:ten is smaller than 5");
console.log(ten < 5);
console.log("test 7:five isequal to 10");
console.log(five == 10);
console.log("test 8:5 is greaterthen 10");
console.log(5 > 10);
console.log("test 9:five is not  equal to 5");
console.log(5 != 5);
console.log("test 10 :1000 is smaller than 500");
console.log(1000 < 500);
